name: apiarist
description: Library for handling api responses in a more nuanced way
version: 1.0.3
repository: https://github.com/jtanium/apiarist

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.0.0
  riverpod: ^2.4.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
