name: apiarist
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/jtanium/apiarist

environment:
  sdk: ^3.0.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.1.2
  riverpod: ^2.4.9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
